app/models/servers.py
from ..extensions import db
from sqlalchemy.dialects.postgresql import INET
from .users import BaseModel
from .hostinfos import HostInfos

class Servers(BaseModel):
    __tablename__ = 'servers'
    server_name = db.Column(db.String(30), unique=True, nullable=False)
    login_id = db.Column(db.String(100), nullable=False)
    ip_address = db.Column(INET, nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False)
    port = db.Column(db.Integer)
    created = db.Column(db.DateTime, default=db.func.current_timestamp())
    id_ip = db.Column(db.String(20))

    # ServerId와 one to one Relationship
    hostinfo = db.relationship('HostInfos', backref='access_info', uselist=False, lazy=True)

    def __init__(self, server_name, ip_address, login_id,  **kwargs):
        super().__init__(server_name=server_name, ip_address=ip_address, login_id=login_id, **kwargs)
        if not self.port:
            self.port = 22
        if not self.id_ip:
            self.id_ip = f"{self.login_id}@{self.ip_address}"

    # SV_INFO와 one to one Relationship
    # sv_info = db.relationship('SV_INFO', backref='server', uselist=False, lazy=True)

    def __repr__(self):
        return f'<Servers {self.id_ip}>'
    

app/routes/servers_routes.py
from flask import (
  Blueprint, request, redirect, 
  render_template as render, flash, url_for) # type: ignore
from flask_login import current_user, login_required # type: ignore
from ..extensions import db
from ..models.servers import Servers
from ..models.users import Users
from .pagenation import pagenation
from sqlalchemy import or_, and_, cast, String # type: ignore

bp = Blueprint("servers_infos", __name__, url_prefix="/health/servers")

@bp.route("/")
def index():
    search_name = request.args.get('server_name', '')
    search_ip = request.args.get('ip_address', '')
    search_user = request.args.get('user', '')

    query = db.session.query(Servers)
    # ========== Search Logic ==========
    # user을 선택한 상태에서 search_name이나 ip_address를 검색하면 and 조건으로 검색
    # user만 선택한 상태에서는 user으로만 검색
    # server_name이나 ip_address만 검색한 상태에서는 or 조건으로 검색
    # INET 형태의 ip_address cast를 통해 String으로 변환 후에 검색
    if search_user and not (search_name or search_ip):
        query = query.join(Servers.operators).filter(Users.username == search_user)
    elif  search_user and (search_name or search_ip):
        filter = []
        if search_name:
            filter.append(Servers.server_name.ilike(f'%{search_name}%'))
        if search_ip:
            filter.append(cast(Servers.ip_address, String).ilike(f'%{search_ip}%'))
        query = query.join(Servers.operators)\
            .filter(Users.username == search_user)\
                .filter(or_(*filter))

    if search_name or search_ip:
        filter = []
        if search_name:
            filter.append(Servers.server_name.ilike(f'%{search_name}%'))
        if search_ip:
            filter.append(cast(Servers.ip_address, String).ilike(f'%{search_ip}%'))
        query = query.filter(or_(*filter))
    # ========== end Search Logic ==========    

    pagination_data = pagenation(query, per_page=10, orders=Servers.id.desc())
    current_user_id = current_user.get_id()
    server_list_by_user = db.session.query(Servers)\
        .join(Servers.operators)\
        .filter(Users.id == current_user_id).all()
    users = db.session.query(Users).all()

    return render("health/servers/index.html", 
        server_list_by_user=server_list_by_user,          
        servers=pagination_data['query_result'], 
        users=users,
        pagenation = pagination_data,
        )

@bp.route("/create", methods=["GET", "POST"])
@login_required
def create_server():
    if request.method == "POST":
        server_name = request.form.get("server_name")
        login_id = request.form.get("login_id")
        ip_address = request.form.get("ip_address")
        port = request.form.get("port")
        password = request.form.get("password")

        if not port:
            port = 22

        if not ip_address or not login_id or not server_name:
            flash("IP 주소, 로그인 ID, 서버 이름은 필수입니다.")
            return render(url_for("servers_infos.create_server"))
        query_existing = db.session.query(Servers).filter_by(ip_address=ip_address).first()
        if query_existing:
            flash("이미 존재하는 서버입니다.")
            return render(url_for("servers_infos.create_server"))

        new_server = Servers(server_name=server_name, login_id=login_id, ip_address=ip_address, port=port, password=password)

        # Get operator IDs from the form and fetch user objects
        operator_ids = request.form.getlist("operators")
        if operator_ids:
            operators = db.session.query(Users).filter(Users.id.in_(operator_ids)).all()
            new_server.operators = operators

        db.session.add(new_server)
        db.session.commit()
        flash(f"Server '{new_server.server_name}' created successfully.")
        return redirect(url_for("servers_infos.index"))
    else:
        users = db.session.query(Users).all()
        return render("health/servers/create_server.html", users=users)

@bp.route("/<int:id>/edit", methods=["GET", "POST"])
@login_required
def edit_server(id):
    server = db.session.query(Servers).filter_by(id=id).first_or_404()
    users = db.session.query(Users).all()

    if request.method == "POST":
        server_name = request.form.get("server_name")
        login_id = request.form.get("login_id")
        ip_address = request.form.get("ip_address")
        port = request.form.get("port")
        password = request.form.get("password")

        if not port:
            port = 22

        if not ip_address or not login_id or not server_name:
            flash("IP 주소, 사용자 이름, 서버 이름은 필수입니다.")
            return render(url_for("servers.edit_server"))
        if server.ip_address != ip_address:
            query_existing = db.session.query(Servers).filter_by(ip_address=ip_address).first()
            if query_existing:
                flash("해당 IP 주소로 등록된 서버가 이미 존재합니다.")
                return render("health/servers/edit_server.html", users=users, server=server)

        server.server_name = server_name
        server.login_id = login_id
        server.ip_address = ip_address
        server.port = port
        server.password = password

        # user에서 operator IDs를 통해 해당 리스트를 검색
        operator_ids = request.form.getlist("operators")
        operators = db.session.query(Users).filter(Users.id.in_(operator_ids)).all()
        server.operators = operators

        db.session.commit()
        flash(f"Server '{server.server_name}' updated successfully.")
        return redirect(url_for("servers_infos.index"))
    return render("health/servers/edit_server.html", users=users, server=server)

@bp.route("/<int:id>/delete", methods=["GET", "POST"])
@login_required
def delete_server(id):
    if request.method == "POST":
        server = db.session.query(Servers).filter_by(id=id).first()
        db.session.delete(server)
        db.session.commit()
        return redirect(url_for("servers_infos.index"))
    else:
        server = db.session.query(Servers).filter_by(id=id).first()
        return render("health/servers/delete_server.html", server=server)

app/templates/health/servers/create_server.html
{% extends 'base.html' %}
{% block title %} Create Server {% endblock %}
{% block header %} Create a New Server {% endblock %}
{% block content %}
 <div class="container mt-4">
    <form method="POST" action="{{ url_for('servers_infos.create_server') }}">
        <div class="form-group">
            <label for="server_name">Server Name</label>
            <input type="text" class="form-control" id="server_name"  name="server_name" required>
        </div>
        <div class="form-group">
            <label for="login_id">Login ID</label>
            <input type="text" class="form-control" id="login_id" name="login_id" required>
        </div>
        <div class="form-group">
            <label for="ip_address">Server IP</label>
            <input type="text" class="form-control" id="ip_address" name="ip_address" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" 
                name="password" placeholder="Leave blank to keep current password">
        </div>
        <div class="form-group">
            <label for="operators">SELECT OPERATORS</label>
            <select multiple class="form-control" id="operators" name="operators" autofocus >
                {% for user in users %}
                    <option value="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
            <small class="form-text text-muted">Ctrl을 누르고 여러개 선택하세요.</small>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Save Server</button>
        <a class="btn btn-secondary mt-3" href="/health/servers/">Cancel</a>
    </form>
</div>

{% endblock %}

app/templates/health/servers/delete_server.html
{% extends 'base.html' %}

{% block title %} Server Health Check {% endblock %}
{% block header %} Delete Server {% endblock %}

{% block content %}
<div class="container mt-4">
  <form method="post" class="form-group d-flex flex-column gap-2 align-items-center" 
    action="/health/servers/{{ server['id'] }}/delete" >
    <p style="margin-top: 2rem;">
      Are you sure you want to delete "{{ server['server_name'] }}"?</p>
    <input class="btn btn-danger" type="submit" value="Delete" 
      onclick="return confirm('Are you sure?');">

    <a class="btn btn-secondary w-100" href="/health/servers/">Cancel</a>
  </form>
</div>
{% endblock %}

app/templates/health/servers/edit_server.html
{% extends 'base.html' %}

{% block title %} Edit Server {% endblock %}
{% block header %} Edit Server: {{ server.server_name }} {% endblock %}

{% block content %}
<div class="container mt-4">
  <form method="POST" action="{{ url_for('servers_infos.edit_server', id=server.id) }}">
    <div class="form-group">
        <label for="server_name">Server Name</label>
        <input type="text" class="form-control" id="server_name" 
            name="server_name" value="{{ server.server_name }}" required>
    </div>
    <div class="form-group">
        <label for="login_id">Login ID</label>
        <input type="text" class="form-control" id="login_id" 
            name="login_id" value="{{ server.login_id }}">
    </div>
    <div class="form-group">
        <label for="ip_address">Server IP</label>
        <input type="text" class="form-control" id="ip_address" 
            name="ip_address" value="{{ server.ip_address }}" required>
    </div>
    <div class="form-group">
        <label for="password">New Password</label>
        <input type="password" class="form-control" id="password" 
            name="password" placeholder="Leave blank to keep current password">
    </div>
    <div>
      <label>Current Operators:</label>
      <ul>
        {% for operator in server.operators %}
            <li>{{ operator.username }}</li>
        {% endfor %}
      </ul>
    </div>
      <div class="form-group">
        <label for="operators">SELECT OPERATORS</label>
        <select multiple class="form-control" id="operators" name="operators" autofocus >
          {% for user in users %}
              {% if user in server.operators %}
                  <option value="{{ user.id }}" selected>{{ user.username }}</option>
              {% else %}
                  <option value="{{ user.id }}">{{ user.username }}</option>
              {% endif %}
          {% endfor %}
        </select>
        <small class="form-text text-muted">Ctrl을 누르고 여러개 선택하세요.</small>
      </div>
      <button type="submit" class="btn btn-primary mt-3">Update Server</button>
    </form>
</div>
{% endblock %}

app/templates/health/servers/index.html
{% extends 'base.html' %}

{% block title %} Server Health Check {% endblock %}
{% block header %} Servers List
   {% if current_user.is_authenticated %}
   <span class="d-flex justify-content-end" style="margin-top:-30px">
     <a class="btn btn-outline-danger fs-sm" href="/health/servers/create">Create Server</a>
   </span>
  {% endif %}
{% endblock %}

{% block content %}
<div class="mt-3 d-flex justify-content-between align-items-center">
  <div>
    <a class="btn btn-outline-primary fs-sm" href="/health/hostinfos/generate">
      Generate HostInfos</a>
  </div>
  <form method="get" action="/health/servers/" accept-charset="utf-8" 
        class="d-flex justify-content-between align-items-center gap-1 fs-sm">
    <select name="user" id="" class="form-select d-inline-block w-auto  fs-sm">
      <option value="">Select User</option>
      {% for user in users %}
        <option value="{{ user.username }}" >{{ user.username }}</option>
      {% endfor %}
    </select>
    <input type="text" name="server_name" placeholder="Server Name" 
      value="{{ server_name }}" class="form-control d-inline-block fs-sm" style="width: 160px;">
    <input type="text" name="ip_address" placeholder="IP Address" 
      value="{{ ip_address }}" class="form-control d-inline-block fs-sm" style="width: 160px;">
    <button type="submit" class="btn btn-outline-secondary fs-sm">Search</button>
    <a class="btn btn-secondary fs-sm" href="/health/servers/">Reset</a>
  </form>
  </div>
  <table class="table table-striped mt-3 w-100 fs-sm">
      <thead class="thead-dark">
          <tr>
              <th>server name</th>
              <th>ID & IP</th>
              <th>Port</th>
              <th>PW</th>
              <th>Operators</th>
              <th>Created</th>
              <th>Hostname from hostinfos</th>
              <th>Edit</th>
              <th>Delete</th>
          </tr>
      </thead>
      <tbody>
        {% if current_user.is_admin %}
          {% for server in servers %}
            <tr>
              {% include 'health/servers/template_server_list.html' %}
            </tr>
          {% endfor %}
        {% else %}
          {% for server in server_list_by_user %}
            <tr>
              {% include 'health/servers/template_server_list.html' %}
            </tr>
          {% endfor %}
        {% endif %}
      </tbody>
    </table>
{# pagenation: target_app, page, total_pages, per_page, page_length, start_page, end_page #}
  {% with 
    target_app='health/servers', 
    page=pagenation.page, 
    total_pages=pagenation.total_pages, 
    per_page=pagenation.per_page, 
    page_length=pagenation.page_len, 
    start_page=pagenation.start_page, 
    end_page=pagenation.end_page %}
      {% include 'pagenation.html' with context %}
  {% endwith %}
{% endblock %}

app/templates/health/servers/server_home.html
{% extends 'base.html' %}

{% block title %} Server Health Check {% endblock %}
{% block header %} Servers List
   {% if current_user.is_authenticated %}
   <span class="d-flex justify-content-end" style="margin-top:-30px">
     <a class="btn btn-outline-danger fs-sm" href="/health/servers/create">Create Server</a>
   </span>
  {% endif %}
{% endblock %}

{% block content %}
<div class="mt-3 d-flex justify-content-between align-items-center">
  <div>
    <a class="btn btn-outline-primary fs-sm" href="/health/hostinfos/generate">
      Generate HostInfos</a>
  </div>
  <form method="get" action="/health/servers/" accept-charset="utf-8" 
        class="d-flex justify-content-between align-items-center gap-1 fs-sm">
    <select name="user" id="" class="form-select d-inline-block w-auto  fs-sm">
      <option value="">Select User</option>
      {% for user in users %}
        <option value="{{ user.username }}" >{{ user.username }}</option>
      {% endfor %}
    </select>
    <input type="text" name="server_name" placeholder="Server Name" 
      value="{{ server_name }}" class="form-control d-inline-block fs-sm" style="width: 160px;">
    <input type="text" name="ip_address" placeholder="IP Address" 
      value="{{ ip_address }}" class="form-control d-inline-block fs-sm" style="width: 160px;">
    <button type="submit" class="btn btn-outline-secondary fs-sm">Search</button>
    <a class="btn btn-secondary fs-sm" href="/health/servers/">Reset</a>
  </form>
  </div>
  <table class="table table-striped mt-3 w-100 fs-sm">
      <thead class="thead-dark">
          <tr>
              <th>server name</th>
              <th>ID & IP</th>
              <th>Port</th>
              <th>PW</th>
              <th>Operators</th>
              <th>Created</th>
              <th>Hostname from hostinfos</th>
              <th>Edit</th>
              <th>Delete</th>
          </tr>
      </thead>
      <tbody>
        {% if current_user.is_admin %}
          {% for server in servers %}
            <tr>
              {% include 'health/servers/template_server_list.html' %}
            </tr>
          {% endfor %}
        {% else %}
          {% for server in server_list_by_user %}
            <tr>
              {% include 'health/servers/template_server_list.html' %}
            </tr>
          {% endfor %}
        {% endif %}
      </tbody>
    </table>
{# pagenation: target_app, page, total_pages, per_page, page_length, start_page, end_page #}
  {% with 
    target_app='health/servers', 
    page=pagenation.page, 
    total_pages=pagenation.total_pages, 
    per_page=pagenation.per_page, 
    page_length=pagenation.page_len, 
    start_page=pagenation.start_page, 
    end_page=pagenation.end_page %}
      {% include 'auth/pagenation.html' with context %}
  {% endwith %}
{% endblock %}

app/templates/health/servers/template_server_form.html
{% if server %}

app/templates/health/servers/template_server_list.html
<td>{{ server['server_name'] }}</td>
<td>{{ server['id_ip'] }}</td>
<td>{{ server['port'] }}</td>
<td>{{ server['password'] }}</td>
<td>
    {% for operator in server.operators %}
        {{ operator.username }}
    {% if not loop.last %}, {% endif %}
    {% endfor %}
</td>
<td>{{ server['created'].strftime('%Y-%m-%d %H:%M') if server['created'] else ''}}</td>
<td>
    {{ server.hostinfo.hostname if server.hostinfo else 'No Hostname' }}
</td>
<td><a class="btn btn-outline-primary fs-sm" href="/health/servers/{{ server['id'] }}/edit">
        Edit</a>
</td>
<td>
    <a class="btn btn-outline-danger fs-sm" href="/health/servers/{{ server['id'] }}/delete">
        Delete</a>
</td>