app/models/commands.py
from ..extensions import db
from .users import BaseModel
import enum

class CAT(str, enum.Enum):
    HOST_INFO = 'host_info' # 서버의 hostname, ip_address 정보를 가져오는 명령어
    SV_INFO = 'sv_info' # 서버의 os_info, total_memory, cpu_cores, uptime 정보를 가져오는 명령어
    SV_SYSCTL = 'sv_sysctl' # 서버의 swappiness, dirty_ratio, overcommit_memory 정보를 가져오는 명령어
    SV_RESOURCES = 'sv_resources' # 서버의 cpu_usage, disk_usage 정보를 가져오는 명령어
    CUSTOM = 'custom' # 사용자 정의 명령어

# no Relationship
class Commands(BaseModel):
    __tablename__ = 'commands'
    category = db.Column(db.Enum(CAT, name='category_enum'), nullable=False)
    name = db.Column(db.String(80), nullable=False, unique=True)
    cmd = db.Column(db.String(100), nullable=False, unique=True)

    def __repr__(self):
        return f'<Commands {self.name}>'

app/routes/commands_bp.py
from flask import (Blueprint, request, render_template as render, 
    redirect, flash, url_for )
from flask_login import login_required # type: ignore
from sqlalchemy import or_, and_ # type: ignore
from ..extensions import db
from ..models.commands import Commands, CAT
from .pagenation import pagenation

bp = Blueprint('commands', __name__, url_prefix='/health/commands')

@bp.route('/')
def index_cmds():
    search_name = request.args.get('search_name', '')
    search_cmd = request.args.get('search_cmd', '')
    selected_category = request.args.get('category', '')

    query = db.session.query(Commands)

    # ========== Search Logic ==========
    # cat을 선택한 상태에서 name이나 cmd를 검색하면 and 조건으로 검색
    # cat만 선택한 상태에서는 cat으로만 검색
    # name이나 cmd만 검색한 상태에서는 or 조건으로 검색
    filters_or = []
    if selected_category and (search_name or search_cmd):
        filters = []
        filters.append(Commands.category == selected_category)
        # if로 분기하는 이유는 and_()에 빈 리스트를 넘기면 에러가 나기 때문
        # if로 안하면 ""이 입력되어 전체 검색을 수행해서 검색이 안됨
        if search_name:
            filters.append(Commands.name.ilike(f'%{search_name}%'))
        if search_cmd:
            filters.append(Commands.cmd.ilike(f'%{search_cmd}%'))
        query = query.filter(and_(*filters))
    elif selected_category and not (search_name and search_cmd):
        filters_or.append(Commands.category == selected_category)
    elif not selected_category and search_name:
        filters_or.append(Commands.name.ilike(f'%{search_name}%'))
    elif not selected_category and search_cmd:
        filters_or.append(Commands.cmd.ilike(f'%{search_cmd}%'))

    if filters_or:
        query = query.filter(or_(*filters_or))
    # ========== end Search Logic ==========

    pg_data = pagenation(query=query, per_page=10, orders=Commands.category.asc())

    categories = [cat.value for cat in CAT]

    return render('health/commands/index.html', 
        categories=categories,
        cmd_list=pg_data['query_result'], 
        pagenation=pg_data,
        selected_category=selected_category, # 실제 역활이 없음
        search_name=search_name, # 실제 역활이 없음
        search_cmd=search_cmd) # 실제 역활이 없음

@bp.route('/create', methods=['GET','POST'])
def create_cmd():
    if request.method == 'POST':
        category = request.form.get("category")
        name = request.form.get("name")
        cmd = request.form.get("cmd")
        if category is None or name is None or cmd is None:
            flash('모든 필드를 채워주세요.', category='alert')
            return render('health/commands/create_cmd.html', categories=[cat.value for cat in CAT])
 
        # Check if a command with the same name OR cmd text already exists.
        existing_cmd = Commands.query.filter(or_(Commands.name == name, Commands.cmd == cmd)).first()
        if existing_cmd:
            flash(f'A command with the same name or command already exists.')
            return render('health/commands/create_cmd.html', categories=[cat.value for cat in CAT])
        
        else:
            new_cmd = Commands(category=category, name=name, cmd=cmd)
            db.session.add(new_cmd)
            db.session.commit()
 
            flash('명령어가 추가되었습니다.!', category='success')
            return redirect(url_for('commands.index_cmds'))
    return render('health/commands/create_cmd.html', 
                  categories=[cat.value for cat in CAT])

@bp.route("/<int:id>/edit", methods=["GET", "POST"])
@login_required
def edit_cmd(id):
    current_cmd = db.session.get(Commands, id)
    if not current_cmd:
        flash("해당 명령어가 없습니다.", category="alert")
        return redirect(url_for("commands.index_cmds")), 404
    if request.method == "POST":
        category = request.form.get("category")
        desc = request.form.get("name")
        cmd = request.form.get("cmd")

        # Check if either name or cmd has changed
        if current_cmd.name != desc or current_cmd.cmd != cmd:
            existing_cmd = Commands.query.filter(or_(Commands.name == desc, Commands.cmd == cmd)).first()
            if existing_cmd:
                flash(f'A command with the same name or command already exists.', category="alert")
                return render('health/commands/edit_cmd.html', cmd=current_cmd, 
                              categories=[cat.value for cat in CAT])

        current_cmd.category = category
        current_cmd.name = desc
        current_cmd.cmd = cmd

        db.session.commit()

        flash("명령어가 수정되었습니다.")
        return redirect(url_for("commands.index_cmds"))
    return render("health/commands/edit_cmd.html", cmd=current_cmd, 
                  categories=[cat.value for cat in CAT])

@bp.route("/<int:id>/delete", methods=["GET", "POST"])
@login_required
def delete_cmd(id):
    cmd = db.session.query(Commands).get(id)
    if request.method == "POST":
        if cmd is None:
            flash("해당 명령어가 없습니다.", category="alert")
            return redirect(url_for("commands.index_cmds"))
        db.session.delete(cmd)
        db.session.commit()
        flash("명령어가 삭제되었습니다.", category="success")
        return redirect(url_for("commands.index_cmds"))
    return render("health/commands/delete_cmd.html", cmd=cmd)

app/templates/health/commands/cmd_home.html
{% extends 'base.html' %}

{% block title %} Server Health Check {% endblock %}
{% block header %} Commands List {% endblock %}

{% block content %}
  <div class="mt-3 d-flex justify-content-between align-items-center">
    <a class="btn btn-outline-primary fs-sm" href="/health/commands/create">Create Command</a>
    <form method="get" action="/health/commands/" accept-charset="utf-8" 
          class="d-flex justify-content-between align-items-center gap-1 fs-sm">
      <select name="category" id="" class="form-select d-inline-block w-auto  fs-sm">
        <option value="">Select Category</option>
        {% for cat in categories %}
          <option value="{{ cat }}" {% if cat == selected_category %}selected{% endif %}>
            {{ cat.split('.')[-1] }}</option>
        {% endfor %}
      </select>
      <input type="text" name="search_name" placeholder="Search Name"
         value="{{ search_name }}" class="form-control d-inline-block fs-sm" style="width: 160px;">
      <input type="text" name="search_cmd" placeholder="Search Command" 
        value="{{ search_cmd }}" class="form-control d-inline-block fs-sm" style="width: 160px;">
      <button type="submit" class="btn btn-outline-secondary fs-sm">Search</button>
      <a class="btn btn-secondary fs-sm" href="/health/commands/">Reset</a>
    </form>
  </div>
  <table class="table table-striped mt-3 fs-sm">
      <thead class="thead-dark">
          <tr>
              <th scope="col">category</th>
              <th scope="col">name</th>
              <th scope="col">command</th>
              <th scope="col">edit</th>
              <th scope="col">delete</th>
          </tr>
      </thead>
      <tbody>
        {% for cmd in cmd_list %}
          <tr>
            <td>{% set category = cmd.category.split('.') %} {{ category[-1] }}</td>
            <td>{{ cmd.name }}</td>
            <td class="text-start">{{ cmd.cmd }}</td>
            <td><a href="{{ url_for('commands.edit_cmd', id=cmd.id) }}" class="btn btn-outline-secondary btn-sm fs-sm">Edit</a></td>
            <td><a href="{{ url_for('commands.delete_cmd', id=cmd.id) }}" class="btn btn-outline-danger btn-sm fs-sm">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{# pagenation: target_app, page, total_pages, per_page, page_length, start_page, end_page #}
  {% with 
    target_app='health/commands', 
    page=pagination.page, 
    total_pages=pagination.total_pages, 
    per_page=pagination.per_page, 
    page_length=pagination.page_len, 
    start_page=pagination.start_page, 
    end_page=pagination.end_page %}
      {% include 'auth/pagenation.html' with context %}
  {% endwith %}
{% endblock %}

app/templates/health/commands/create_cmd.html
{% extends 'base.html' %}
{% block title %} Create Command {% endblock %}
{% block header %} Create a New Command {% endblock %}
{% block content %}
 <div class="container mt-4">
    <form method="POST" action="{{ url_for('commands.create_cmd') }}">
        <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" id="category" name="category" required>
                    <option value="">Select Category</option>
                {% for category in categories %}
                    <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
        <div class="form-group">
            <label for="cmd">Command</label>
            <input type="text" class="form-control" id="cmd" name="cmd" required>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Create Command</button>
        <a class="btn btn-secondary  mt-3" href="/health/commands/">Cancel</a>
    </form>
</div>

{% endblock %}

app/templates/health/commands/delete_cmd.html
{% extends 'base.html' %}

{% block title %} Server Health Check {% endblock %}
{% block header %} Delete Server {% endblock %}

{% block content %}
<div class="container mt-4">
  <form method="post" class="form-group d-flex flex-column gap-2 align-items-center" 
    action="/health/commands/{{ cmd.id }}/delete" >
    <p style="margin-top: 2rem;">
      Are you sure you want to delete "{{ cmd.name }}"?</p>
    <input class="btn btn-danger w-50" type="submit" value="Delete" 
      onclick="return confirm('Are you sure?');">

    <a class="btn btn-secondary mt-3" href="/health/commands/">Cancel</a>
  </form>
</div>
{% endblock %}

app/templates/health/commands/edit_cmd.html
{% extends 'base.html' %}
{% block title %} Edit Command {% endblock %}
{% block header %} Edit Command {% endblock %}
{% block content %}
 <div class="container mt-4">
    <form method="POST" action="{{ url_for('commands.edit_cmd', id=cmd.id) }}">
        <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" id="category" name="category" required>
                    <option value="">Select Category</option>
                {% for category in categories %}
                    <option value="{{ category }}" 
                    {% if cmd.category.value == category %} selected {% endif %}>
                      {{ category }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ cmd.name }}" required>
        </div>
        <div class="form-group">
            <label for="cmd">Command</label>
            <input type="text" class="form-control" id="cmd" name="cmd" value="{{ cmd.cmd }}" required>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Update Command</button>
        <a class="btn btn-secondary mt-3" href="/health/commands/">Cancel</a>
    </form>
</div>
{% endblock %}

app/templates/health/commands/index.html
{% extends 'base.html' %}

{% block title %} Server Health Check {% endblock %}
{% block header %} Commands List {% endblock %}

{% block content %}
  <div class="mt-3 d-flex justify-content-between align-items-center">
    <a class="btn btn-outline-primary fs-sm" href="/health/commands/create">Create Command</a>
    <form method="get" action="/health/commands/" accept-charset="utf-8" 
          class="d-flex justify-content-between align-items-center gap-1 fs-sm">
      <select name="category" id="" class="form-select d-inline-block w-auto  fs-sm">
        <option value="">Select Category</option>
        {% for cat in categories %}
          <option value="{{ cat }}" {% if cat == selected_category %}selected{% endif %}>
            {{ cat.split('.')[-1] }}</option>
        {% endfor %}
      </select>
      <input type="text" name="search_name" placeholder="Search Name"
         value="{{ search_name }}" class="form-control d-inline-block fs-sm" style="width: 160px;">
      <input type="text" name="search_cmd" placeholder="Search Command" 
        value="{{ search_cmd }}" class="form-control d-inline-block fs-sm" style="width: 160px;">
      <button type="submit" class="btn btn-outline-secondary fs-sm">Search</button>
      <a class="btn btn-secondary fs-sm" href="/health/commands/">Reset</a>
    </form>
  </div>
  <table class="table table-striped mt-3 fs-sm">
      <thead class="thead-dark">
          <tr>
              <th scope="col">category</th>
              <th scope="col">name</th>
              <th scope="col">command</th>
              <th scope="col">edit</th>
              <th scope="col">delete</th>
          </tr>
      </thead>
      <tbody>
        {% for cmd in cmd_list %}
          <tr>
            <td>{% set category = cmd.category.split('.') %} {{ category[-1] }}</td>
            <td>{{ cmd.name }}</td>
            <td class="text-start">{{ cmd.cmd }}</td>
            <td><a href="{{ url_for('commands.edit_cmd', id=cmd.id) }}" class="btn btn-outline-secondary btn-sm fs-sm">Edit</a></td>
            <td><a href="{{ url_for('commands.delete_cmd', id=cmd.id) }}" class="btn btn-outline-danger btn-sm fs-sm">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{# pagenation: target_app, page, total_pages, per_page, page_length, start_page, end_page #}
  {% with 
    target_app='health/commands', 
    page=pagenation.page, 
    total_pages=pagenation.total_pages, 
    per_page=pagenation.per_page, 
    page_length=pagenation.page_len, 
    start_page=pagenation.start_page, 
    end_page=pagenation.end_page %}
      {% include 'pagenation.html' with context %}
  {% endwith %}
{% endblock %}